SOLVER:
  OPTIMIZER_NAME: "Adam"
  BASE_LR: 0.0012 # 12
  WEIGHT_DECAY: 0. # 0.0000001
  IMS_PER_BATCH: 1
  START_ITERS: 2000
  END_ITERS: 50000
  LR_SCALE: 0.08
  WARMUP_ITERS: 1000

  LOSS_FN: "L1"    # L1 or L2

  MAX_EPOCHS: 200
  CHECKPOINT_PERIOD: 5000
  LOG_PERIOD: 30
  BUNCH: 60000
  BATCH_SIZE: 8 # 12
  COARSE_STAGE: 0

  USE_AMP: True
  SEED: 2021

INPUT:
  SIZE_TRAIN: [960,540]
  SIZE_TEST: [960,540]

DATASETS:
  TYPE: "NR" # "NR"   "LLFF"
  SYNTHESIS: True

 TRAIN: "wolf"
 TEST: "wolf"

  NUM_FRAME: 48
  NUM_CAMERA: 24 # 24
  SHIFT: 0.0
  MAXRATION: 0.0
  ROTATION: 0.0

  USE_MASK: False
  USE_DEPTH: True
  USE_ALPHA: True

  PAIR_SAMPLE: False

DATALOADER:
  NUM_WORKERS: 20

MODEL:
  USE_MOTION: True
  USE_RENDER_NET: True
  USE_LIGHT_RENDERER: False

  USE_SH: True
  SH_DIM: 9
  SH_FEAT_DIM: 10
  BONE_FEAT_DIM: 10
  TREE_DEPTH: 8
  RANDOM_INI: True

  PAIR_TRAINING: False

TEST:
  IMS_PER_BATCH: 1

OUTPUT_DIR: ""




